SELECT 
    "OPERACION" AS OPERACION,
    "TRANSACCION" AS TRANSACCION,
    "FFECHAOPERACION" AS FECHA_OPERACION,
    "HHORAOPERACION" AS HORA_OPERACION, 
    "NOMBRE DIA" AS NOMBRE_DIA_OPERACION,
    "AREA_VENTA" AS AREA_VENTA,
    "ANOMBRECLASESERVICIO" AS CLASE_SERVICIO,
    "ORIGEN" AS ORIGEN,
    "DESTINO" AS DESTINO,
    "CLAVE CORRIDA" AS CV_CORRIDA,
    "FECHA_CORRIDA" AS FECHA_CORRIDA,
    "HORA_SALIDA_CORRIDA" AS HORA_SALIDA_CORRIDA,
    "TIPO PASAJERO" AS TIPO_PASAJERO,
    "TIPO_CLIENTE" AS TIPO_CLIENTE,
    "TIPO_OPERACION" AS TIPO_OPERACION,
    "VENTA_ANTICIPADA" AS VENTA_ANTICIPADA,
    "NOMBRE_PASAJERO" AS NOMBRE_PASAJERO,
    "NUMERO ASIENTO" AS NUM_ASIENTO,
    "% PROMOCION" AS PORCENT_PROMO,
    "DESCRIPCION_DESCUENTO" AS DESC_DESCUENTO,
    "BOLETOS_CANCELADOS" AS BOLETOS_CANCEL,
    "BOLETOS_VENDIDOS" AS BOLETOS_TOTALES,
    ( "BOLETOS_VENDIDOS" - "BOLETOS_CANCELADOS" ) AS BOLETOS_VEND,
    "CANCELACION" AS VENTA_CANCEL,
    "IVA_CANCELADO" AS IVA_CANCEL,
    "IVA_VENDIDO" AS IVA_VENDIDO,
    "VENTA" AS VENTA_TOTAL,
    ( ( "VENTA" - "IVA_VENDIDO" ) - ( "CANCELACION" - "IVA_CANCELADO" ) ) AS VENTA
FROM DATA
WHERE 
    "ORIGEN" IN ( VAR_ORIG_SQL ) AND
    "DESTINO" IN ( VAR_DEST_SQL ) AND 
    "TIPO_OPERACION" IN ( 'AM', 'BM', 'CE', 'CS', 'NE', 'NS' ) AND
    "ANIO" >= '2023'
