SELECT 
	VT.NCLAVEOPERACION AS OPERACION,
	VT.ATELEFONOPASAJERO AS TEL_PASAJERO,
	VC.ACORREOELECTRONICO AS CORREO_ELECTRONICO,
	VC.AIDMEMBRESIACRM AS MEMBRESIA_CRM,
	VT.ACLAVEOFICINAORIGEN AS ORIGEN,
	VT.ACLAVEOFICINADESITINO AS DESTINO,
	VT.FFECHAOPERACION AS FECHA_OPERACION,
	VT.HHORAOPERACION AS HORA_OPERACION
FROM VTOPEACTIVASTRANSA AS VT
LEFT JOIN VTOPEACTIVASTRANSACOMPLEMENTO AS VC
	ON VT.NCLAVEOPERACION = VC.NCLAVEOPERACION 
	AND VT.NCLAVETRANSACCION = VC.NCLAVETRANSACCION 
WHERE VT.FFECHASALIDAINICIO >= DATE('2023-01-01')
    AND ACLAVEOFICINAORIGEN IN ( VAR_ORIG_SQL )
    AND ACLAVEOFICINADESITINO IN ( VAR_DEST_SQL )
	AND ACLAVETIPOOPERACION IN ( 'AM', 'BM', 'CE', 'CS', 'NE', 'NS' )
	AND NCLAVEOPERACIONVP = 0