SELECT 
    "TRANSACCION" AS TRANSACCION,
    "FECHA OPERACION" AS FECHA_OPERACION,
    "FECHA SALIDA INICIO" AS FECHA_CORRIDA,
    "ORIGEN" AS ORIGEN,
    "DESTINO" AS DESTINO,
    "TERMINAL" AS TARJETA,
    "EFECTIVO" AS EFECTIVO,
    "EMAIL" AS EMAIL
FROM DATA
WHERE 
    "ORIGEN" IN ( VAR_ORIG_SQL ) AND
    "DESTINO" IN ( VAR_DEST_SQL ) AND 
    "AÑO" >= '2023'
