SELECT 
    "ANIO-MES-DIA" AS FECHA_CORRIDA,
    "CORRIDA" AS CV_CORRIDA,
    "CLAVEASIGNACION" AS CV_ASIGN,
    "CV ORIGEN CORRIDA" AS ORIGEN_CORRIDA,
    "CV DESTINO CORRIDA" AS DESTINO_CORRIDA,
    "HORA SALIDA ORIGEN RUTA" AS HORA_SALIDA_ORIGEN_CORRIDA,
    "NKILOMETROSACUMULADOSRUTAS" AS KMS_ACUM_CORRIDA,
    "CLAVE TRAMO ORIGEN" AS ORIGEN,
    "CLAVE TRAMO DESTINO" AS DESTINO,
    "HORA SALIDA PUNTO" AS HORA_SALIDA_CORRIDA,
    "NOMDIA" AS NOMBRE_DIA_CORRIDA,
    "EMPRESA SERVICIO" AS EMPRESA,
    "TIPO CORRIDA" AS TIPO_CORRIDA,
    "TIPO AUTOBUS" AS TIPO_BUS,
    "TARIFABASETRAMO" AS TARIFA_BASE_TRAMO,
    "NIVATARIFABASETRAMO" AS IVA_TARIFA_BASE_TRAMO,
    "INGRESOS" AS INGRESO_TRANSP,
    "IVA" AS IVA_TRANSP,
    "KILOMETROS_TRAMOS" AS KMS_TRAMO,
    "NCAPACIDADASIENTOTRAMO" AS CAPACIDAD_ASIENTOS_TRAMO,
    "DISPONIBILIDAD_TRAMO" AS DISPONIBILIDAD_TRAMO,
    "OCUPACIONPUNTO" AS OCUPACION_TRAMO,
    "PASAJEROS BAJAN EN ORIGEN" AS PAX_BAJAN,
    "PASAJEROS SUBEN EN ORIGEN" AS PAX_SUBEN
FROM DATA
WHERE 
    "CLAVE TRAMO ORIGEN" IN ( VAR_ORIG_SQL ) AND
    "CLAVE TRAMO DESTINO" IN ( VAR_DEST_SQL ) AND 
    "ANIO" >= '2023'
