SELECT
    "EMPRESA_SERVICIO" AS EMPRESA,
    "AÑO" AS ANIO, 
    "FECHA",
    "TIPO OPERACION" AS TIPO_OPERACION,
    SUM("VENTA") AS VENTA, 
    SUM("BOLETOS") AS BOLETOS
FROM DATA
WHERE ("TIPO OPERACION" = 'BOLETOS' OR 
    "TIPO OPERACION" = 'PACK') AND 
    ("AÑO" >= '2023') AND 
    "EMPRESABTRANSPORTA" NOM_EMPRESA
GROUP BY 
    "AÑO", 
    "FECHA",
    "TIPO OPERACION"
ORDER BY "FECHA"