SELECT
    "EMPRESA_SERVICIO" AS EMPRESA,
    "ANIO" AS ANIO, 
    "ANIO-MES" AS ANIO_MES,
    "ANIO-MES-DIA" AS FECHA, 
    SUM("INGRESOS") AS INGRESO,
    SUM("NKILOMETROSACUMULADOSRUTAS") AS KMS,
    SUM("PASAJEROS SUBEN EN ORIGEN") AS PAX
FROM DATA
WHERE 
    ("ANIO" >= '2023') 
GROUP BY 
    "ANIO", 
    "ANIO-MES",
    "ANIO-MES-DIA"
ORDER BY FECHA