SELECT
    "EMPRESA" AS EMPRESA,
    "FECHA" AS FECHA,
    "TIPO OPERACION" AS TIPO_OPERACION,
    SUM("PRESUPUESTO") AS PTTO,
    SUM("PASAJEROS") AS PTTO_PAX,
    SUM("KMS") AS PTTO_KM,
    SUM("SERVICIOS") AS PTTO_SERVICIOS
FROM DATA
GROUP BY "EMPRESA", "FECHA", "TIPO OPERACION"