SELECT
    EMPRESA_SERVICIO AS EMPRESA,
    "FECHA" AS FECHA,
    "TIPO OPERACION" AS TIPO_OPERACION,
    SUM("VENTA") AS PTTO,
    SUM("BOLETOS") AS PTTO_PAX,
    SUM("PRESUPUESTO MENSUAL") AS PTTO_KM,
    SUM("PRESUPUESTO MENSUAL") AS PTTO_SERVICIOS
FROM DATA
WHERE "EMPRESA B INGRESO" NOM_EMPRESA
GROUP BY "FECHA", "TIPO OPERACION"