SELECT
    "EMPRESA_SERVICIO" AS EMPRESA,
    "ANIO", 
    "ANIO-MES" AS ANIO_MES,
    "ANIO-MES-DIA" AS FECHA, 
    SUM("OCUPACION_TRAMO") AS OCUPACION,
    ( SUM("KILOMETROPUNTOxOCUPACION") / SUM("KILOMETROPUNTOxCAPACIDADASIENTO") ) AS FOP,
    SUM("CUENTACORRIDA") AS CORRIDAS
FROM DATA
WHERE 
    ("ANIO" >= '2023') AND 
    "EMPRESA SERVICIO" NOM_EMPRESA
GROUP BY 
    "ANIO", 
    "ANIO-MES",
    "ANIO-MES-DIA"
ORDER BY FECHA